//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelayRepay_BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public Destination()
        {
            this.FromStations = new HashSet<FromStation>();
        }
    
        public int Id { get; set; }
        public int JourneyId { get; set; }
        public int StationId { get; set; }
        public System.DateTime ScheduledArrival { get; set; }
        public System.DateTime ActualArrival { get; set; }
        public Nullable<int> EmailBatchId { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual Station Station { get; set; }
        public virtual ICollection<FromStation> FromStations { get; set; }
        public virtual EmailBatch EmailBatch { get; set; }
    }
}
