//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelayRepay_BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FromStation
    {
        public int Id { get; set; }
        public int DestinationId { get; set; }
        public int StationId { get; set; }
        public System.DateTime ScheduledDeparture { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Station Station { get; set; }
    }
}
