//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelayRepay_BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public Journey()
        {
            this.Destinations = new HashSet<Destination>();
        }
    
        public int Id { get; set; }
        public string JCode { get; set; }
        public string TrainOperator { get; set; }
    
        public virtual ICollection<Destination> Destinations { get; set; }
    }
}
