//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelayRepay_BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int FormsAuthUserID { get; set; }
        public int HomeStationId { get; set; }
        public int DestinationStationId { get; set; }
        public string EMail { get; set; }
    
        public virtual Station HomeStation { get; set; }
        public virtual Station DestinationStation { get; set; }
    }
}
